apiVersion: {{.Group}}/{{.Version}}
kind: {{.CodeServer}}
metadata:
  name: {{.Name}}
  namespace: {{.NameSpace}}
  labels:
      {{range $key, $value := .Labels}}
        {{$key}}: {{$value}}
        {{end}}

spec:
  runtime: generic
  subdomain: {{.Name}}
  image: {{.Image}}
  storageSize: {{.StorageSize}}Gi
  storageName: emptyDir
  inactiveAfterSeconds: 0
  recycleAfterSeconds: {{.RecycleSeconds}}
  restartPolicy: Never
  nodeSelector:
    jupyter: "true"
  resources:
    requests:
      cpu: "{{.CPU}}"
      memory: {{.Memory}}
    limits:
      cpu: "{{.CPU}}"
      memory: {{.Memory}}
  connectProbe: /
  enableOauth2Proxy: true
  workspaceLocation: /workspace
  containerPort: "{{.ContainerPort}}"
  envs:
    - name: JUPYTER_SERVER_PORT
      value: "{{.ContainerPort}}"
    - name: JUPYTER_SERVER_NAME
      value: "0.0.0.0"
    - name: USER
      value: "{{.User}}"
    - name: ACCESS_TOKEN_ENDPOINT
      value: "{{.AccessTokenEndpoint}}"
    - name: USER_POOL
      value: "{{.UserPoolId}}"
